IMAGE_NAME = "ubuntu/focal64"
MASTERS_NUM = 1
MASTERS_CPU = 2 
MASTERS_MEM = 2048
NAME = "ubuntu-base"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = IMAGE_NAME
    config.vm.network  "public_network"
    config.vm.hostname = NAME
    config.vm.synced_folder  ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v|
        v.name = NAME
        v.memory = MASTERS_MEM
        v.cpus = MASTERS_CPU
    end
    config.vm.provision "shell", path: "init.sh"
end
