IMAGE_NAME = "base-docker"
MASTERS_CPU = 4
MASTERS_MEM = 4096

NAME = "jfrog-jcr"

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.vm.box = IMAGE_NAME
    config.vm.network  "public_network",bridge:"enp5s0",ip: "10.2.10.66"
    config.vm.hostname = NAME
    config.vm.synced_folder  ".", "/vagrant"
    config.vm.provider "virtualbox" do |v|
        v.name = NAME
        v.memory = MASTERS_MEM
        v.cpus = MASTERS_CPU
    end
    config.vm.provision "shell", path: "init.sh"
end
