IMAGE_NAME = "ubuntu/focal64"
CPU = 4
MEM = 8192:
NAME = "jump-server"

Vagrant.configure("2") do |config|
    config.vm.box = IMAGE_NAME
    config.vm.network  "public_network" ,ip:"192.168.31.88"
    config.vm.hostname = NAME
    config.vm.synced_folder  ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |v|
        v.name = NAME
        v.memory = MEM
        v.cpus = CPU
    end
end