IMAGE_NAME = "base-k8s"
MASTERS_NUM = 1
MASTERS_CPU = 2 
MASTERS_MEM = 4096
MASTERS_IP="192.168.1.110"

NODES_NUM = 2
NODES_CPU = 1
NODES_MEM = 4096

Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box = IMAGE_NAME
      master.vm.hostname = "master"
      master.vm.network  "public_network" , ip: MASTERS_IP
      master.vm.provider "virtualbox" do |v|
          v.name="k8s-master"
          v.memory = MASTERS_MEM
          v.cpus = MASTERS_CPU
      end
      master.vm.provision "shell", path: "master.sh"
      master.vm.provision "ansible" do |ansible|
        ansible.playbook = "base-services/gitlab/playbook/main.yaml"
      end
    end

    (1..NODES_NUM).each do |i|
        config.vm.define "node0#{i}" do |node|
          node.vm.box = IMAGE_NAME
          node.vm.hostname = "node0#{i}"
          node.vm.network "public_network"
          node.vm.provider "virtualbox" do |v|
              v.name = "k8s-node-0#{i}"
              v.memory = NODES_MEM
              v.cpus = NODES_CPU
          end
          node.vm.provision "shell", path: "node.sh"
        end
    end
end