IMAGE_NAME = "base-k8s"
MASTERS_NUM = 1
MASTERS_CPU = 4
MASTERS_MEM = 8192
MASTERS_IP="192.168.31.88"

NODES_NUM = 3
NODES_CPU = 4
NODES_MEM = 8192

Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.ssh.username = 'root'
      master.ssh.password = 'root'
      master.ssh.insert_key = 'true'
      master.vm.box = IMAGE_NAME
      master.vm.hostname = "master"
      master.vm.network  "public_network" , ip: MASTERS_IP
      master.vm.provider "virtualbox" do |v|
          v.name="k8s-master"
          v.memory = MASTERS_MEM
          v.cpus = MASTERS_CPU
      end
      master.vm.provision "shell", path: "master.sh"
    end
    (1..NODES_NUM).each do |i|
        config.vm.define "node0#{i}" do |node|
          node.ssh.username = 'root'
          node.ssh.password = 'root'
          node.ssh.insert_key = 'true'
          node.vm.box = IMAGE_NAME
          node.vm.hostname = "node0#{i}"
          node.vm.network "public_network",ip:"192.168.31.11#{i}"
          node.vm.provider "virtualbox" do |v|
              v.name = "k8s-node-0#{i}"
              v.memory = NODES_MEM
              v.cpus = NODES_CPU
          end
          node.vm.provision "shell", path: "node.sh"
        end
    end
end